# delimit ;

clear all;
clear matrix;
set mem 800m;
set more off;



cd "C:\Users\lkarabar\Desktop\ChicagoBooth\Research\Time Use\Data\MyData\ATUS Data\Data for Publication\Results Aggregate Trends";
 
use all_atus;

tabout year if year==2003  & age<=65 &age>=18 & other==0           [aw=weight_adj] using aggregate_trends_temp.xls, replace format(8) ptotal(none) lines (none)                        sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2004  & age<=65 &age>=18 & other==0           [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2005  & age<=65 &age>=18 & other==0           [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2006  & age<=65 &age>=18 & other==0           [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2007  & age<=65 &age>=18 & other==0           [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2008  & age<=65 &age>=18 & other==0           [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2009  & age<=65 &age>=18 & other==0           [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2010  & age<=65 &age>=18 & other==0           [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
/*Men:*/
tabout year if year==2003  & age<=65 &age>=18 & other==0 &male==1  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2004  & age<=65 &age>=18 & other==0 &male==1  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2005  & age<=65 &age>=18 & other==0 &male==1  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2006  & age<=65 &age>=18 & other==0 &male==1  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2007  & age<=65 &age>=18 & other==0 &male==1  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2008  & age<=65 &age>=18 & other==0 &male==1  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2009  & age<=65 &age>=18 & other==0 &male==1  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2010  & age<=65 &age>=18 & other==0 &male==1  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
/*Women:*/
tabout year if year==2003  & age<=65 &age>=18 & other==0 &male==0  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2004  & age<=65 &age>=18 & other==0 &male==0  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2005  & age<=65 &age>=18 & other==0 &male==0  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2006  & age<=65 &age>=18 & other==0 &male==0  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2007  & age<=65 &age>=18 & other==0 &male==0  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2008  & age<=65 &age>=18 & other==0 &male==0  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2009  & age<=65 &age>=18 & other==0 &male==0  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);
tabout year if year==2010  & age<=65 &age>=18 & other==0 &male==0  [aw=weight_adj] using aggregate_trends_temp.xls, append format(8) h1(nil) h2(nil) h3(nil) ptotal(none) lines (none) sum cells(N work_paper mean year mean male mean age mean spouse_emp mean married mean black mean hv_child mean num_child mean grade mean working mean unemp mean retired mean disabled mean student mean homemaker  mean work_paper mean worka_paper mean worku_paper mean leisure_paper mean ep_paper mean sleeping_paper mean esp_paper mean tv_paper mean otherleisure_paper mean socializing_paper mean home_paper mean homeproduction_paper mean homeown_paper mean shopping_paper mean othercare_paper mean childcare_paper mean other_paper mean education_paper mean civic_paper mean ownmedical_paper mean unclassified_paper) show(none);






